import { Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "../components/core/Navbar";

const font = Orbitron({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={font.className + " h-screen bg-background text-secondary"}
      >
        <Navbar />
        <main className="flex flex-col p-8">{children}</main>
      </body>
    </html>
  );
}
